[versions]
# Minecraft
spigot = "1.21.4-R0.1-SNAPSHOT"

# Adventure
minimessage = "4.16.0"
adventure-platform = "4.3.4"

# Other
configurate = "4.1.2"
cmds = "2.0.0-SNAPSHOT"
papi = "2.11.6"
towny = "0.98.1.3"
discordsrv = "1.25.1"
supervanish = "6.2.17"
bstats = "3.0.0"
essentials = "2.19.4"
griefprevention = "16.18.1"

[libraries]
# Minecraft
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }

# Adventure
adventure-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-configurate = { module = "net.kyori:adventure-serializer-configurate4", version.ref = "adventure-platform" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "minimessage" }

# Other
configurate = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
triumph-cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version.ref = "cmds" }
papi = { module = "me.clip:placeholderapi", version.ref = "papi" }
towny = { module = "com.palmergames.bukkit.towny:towny", version.ref = "towny" }
discordsrv = { module = "com.discordsrv:discordsrv", version.ref = "discordsrv" }
supervanish = { module = "com.github.LeonMangler:SuperVanish", version.ref = "supervanish" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
essentials = { module = "net.essentialsx:EssentialsX", version.ref="essentials" }
griefprevention = { module = "com.github.TechFortress:GriefPrevention", version.ref = "griefprevention"}
